-- --------------------------------------------------------
-- Host:                         bioed-new.bu.edu
-- Server version:               11.4.5-MariaDB - MariaDB Server
-- Server OS:                    Linux
-- HeidiSQL Version:             12.10.0.7010
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table Team11.gapfill_models: ~126 rows (approximately)
INSERT INTO `gapfill_models` (`id`, `Species_Name`, `growth_media`, `gapfill_algorithm`, `annotation_tool`, `file_name`, `file_link`, `growth_data`, `growth_file`, `biomass_file_5mM`, `biomass_file_20mM`) VALUES
	(1, 'P.simiae', 'D-Glucose', 'Model SEED', 'prokka', 'PS_prokka_gapfilled_D-Glucose.xml', 'xml_files/PS_prokka_gapfilled_D-Glucose.xml', 'Growth', 'growth_file/RCH2_D-Glucose.tsv', '5mM/5mM_d-glucose.tsv', '20mM/20mM_d-glucose.tsv'),
	(2, 'P.simiae', 'd-arabinose', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_d-arabinose.xml', 'xml_files/PS_glucose-minimal_gapfilled_d-arabinose.xml', 'Growth', 'growth_file/RCH2-L-Arabinose.tsv', '5mM/5mM_d-arabinose.tsv', '20mM/20mM_d-arabinose.tsv'),
	(3, 'P.simiae', 'AKGDSH', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_AKGDSH.xml', 'xml_files/PS_glucose-minimal_gapfilled_AKGDSH.xml', 'Growth', NULL, NULL, NULL),
	(4, 'P.simiae', 'RCH2-fructose', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-fructose.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-fructose.xml', 'Growth', 'growth_file/RCH2-D-Fructose.tsv', '5mM/5mM_d-fructose.tsv', '20mM/20mM_d-fructose.tsv'),
	(6, 'P.simiae', 'citrulline', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_citrulline.xml', 'xml_files/PS_glucose-minimal_gapfilled_citrulline.xml', 'Growth', 'growth_file/RCH2-Citrulline.tsv', '5mM/5mM_l-citrulline.tsv', '20mM/20mM_l-citrulline.tsv'),
	(8, 'P.simiae', 'citrate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_citrate.xml', 'xml_files/PS_glucose-minimal_gapfilled_citrate.xml', 'Growth', 'growth_file/RCH2-Citrate.tsv', '5mM/5mM_trisodium_citrate_dihydrate.tsv', '20mM/20mM_trisodium_citrate_dihydrate.tsv'),
	(9, 'P.simiae', 'glucuronate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_glucuronate.xml', 'xml_files/PS_glucose-minimal_gapfilled_glucuronate.xml', 'Growth', 'growth_file/RCH2-Glucuronate.tsv', NULL, NULL),
	(10, 'P.simiae', 'GluconicAcid', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_GluconicAcid.xml', 'xml_files/PS_glucose-minimal_gapfilled_GluconicAcid.xml', 'Growth', NULL, NULL, NULL),
	(11, 'P.simiae', 'd-lactate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_d-lactate.xml', 'xml_files/PS_glucose-minimal_gapfilled_d-lactate.xml', 'Growth', 'growth_file/RCH2-D-Lactate.tsv', '5mM/5mM_sodium_d-lactate.tsv', '20mM/20mM_sodium_d-lactate.tsv'),
	(12, 'P.simiae', 'cytidine', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_cytidine.xml', 'xml_files/PS_glucose-minimal_gapfilled_cytidine.xml', 'Growth', 'growth_file/RCH2-Cytidine.tsv', '5mM/5mM_cytidine.tsv', '20mM/20mM_cytidine.tsv'),
	(14, 'P.simiae', 'RCH2-L-Phenylalanine', 'Model SEED', 'RASTtk', 'PS_RASTtk_gapfilled_RCH2-L-Phenylalanine.xml', 'xml_files/PS_RASTtk_gapfilled_RCH2-L-Phenylalanine.xml', 'Growth', 'growth_file/RCH2-L-Phenylalanine.tsv', '5mM/5mM_l-phenylalanine.tsv', '20mM/20mM_l-phenylalanine.tsv'),
	(15, 'P.simiae', 'RCH2-L-Tryptophan', 'Model SEED', 'RASTtk', 'PS_RASTtk_gapfilled_RCH2-L-Tryptophan.xml', 'xml_files/PS_RASTtk_gapfilled_RCH2-L-Tryptophan.xml', 'Growth', 'growth_file/RCH2-L-Tryptophan.tsv', '5mM/5mM_l-tryptophan.tsv', '20mM/20mM_l-tryptophan.tsv'),
	(16, 'P.simiae', 'GOE-RCH2-octanoate', 'Model SEED', 'RASTtk', 'PS_RASTtk_gapfilled_GOE-RCH2-octanoate.xml', 'xml_files/PS_RASTtk_gapfilled_GOE-RCH2-octanoate.xml', 'Growth', 'growth_file/RCH2-octanoate.tsv', '5mM/5mM_sodium_octanoate.tsv', '20mM/20mM_sodium_octanoate.tsv'),
	(18, 'P.simiae', 'RCH2-acetate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-acetate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-acetate.xml', 'Growth', NULL, '5mM/5mM_potassium_acetate.tsv', '20mM/20mM_potassium_acetate.tsv'),
	(19, 'P.simiae', 'RCH2-D-Galacturonate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-D-Galacturonate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-D-Galacturonate.xml', 'Growth', 'growth_file/RCH2-D-Galacturonate.tsv', NULL, NULL),
	(20, 'P.simiae', 'RCH2-D-Mannitol', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-D-Mannitol.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-D-Mannitol.xml', 'Growth', 'growth_file/RCH2-D-Mannitol.tsv', '5mM/5mM_d-mannitol.tsv', '20mM/20mM_d-mannitol.tsv'),
	(21, 'P.simiae', 'RCH2-L-Inositol', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-L-Inositol.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-L-Inositol.xml', 'Growth', 'growth_file/RCH2-L-Inositol.tsv', NULL, NULL),
	(22, 'P.simiae', 'RCH2-N-Acetyl-D-glucosamine', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-N-Acetyl-D-glucosamine.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-N-Acetyl-D-glucosamine.xml', 'Growth', 'growth_file/RCH2-N-Acetyl-D-glucosamine.tsv', '5mM/5mM_n-acetyl-d-glucosamine.tsv', '20mM/20mM_n-acetyl-d-glucosamine.tsv'),
	(23, 'P.simiae', 'RCH2-Propionate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-Propionate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-Propionate.xml', 'Growth', 'growth_file/RCH2-Propionate.tsv', '5mM/5mM_sodium_propionate.tsv', '20mM/20mM_sodium_propionate.tsv'),
	(24, 'P.simiae', 'RCH2-Succinate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-Succinate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-Succinate.xml', 'Growth', 'growth_file/RCH2-Succinate.tsv', '5mM/5mM_sodium_succinate_dibasic_hexahydrate.tsv', '20mM/20mM_sodium_succinate_dibasic_hexahydrate.tsv'),
	(25, 'P.simiae', 'RCH2-Uridine', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-Uridine.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-Uridine.xml', 'Growth', 'growth_file/RCH2-Uridine.tsv', '5mM/5mM_uridine.tsv', '20mM/20mM_uridine.tsv'),
	(26, 'P.simiae', 'RCH2-Xylitol', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-Xylitol.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-Xylitol.xml', 'Growth', 'growth_file/RCH2-Xylitol.tsv', '5mM/5mM_xylitol.tsv', '20mM/20mM_xylitol.tsv'),
	(27, 'P.simiae', 'RCH2-TRHL-2', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-TRHL-2.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-TRHL-2.xml', 'Growth', NULL, NULL, NULL),
	(28, 'P.simiae', 'itaconate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_itaconate.xml', 'xml_files/PS_glucose-minimal_gapfilled_itaconate.xml', 'Growth', 'growth_file/RCH2-Itaconate.tsv', NULL, NULL),
	(30, 'P.simiae', 'RCH2-itaconate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-itaconate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-itaconate.xml', 'Growth', 'growth_file/RCH2-Itaconate.tsv', NULL, NULL),
	(31, 'P.simiae', 'RCH2-larabinose', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-larabinose.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-larabinose.xml', 'Growth', NULL, NULL, NULL),
	(32, 'P.simiae', 'RCH2-L-Lactate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-L-Lactate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-L-Lactate.xml', 'Growth', 'growth_file/RCH2-L-Lactate.tsv', '5mM/5mM_sodium_d,l-lactate.tsv', '20mM/20mM_sodium_d,l-lactate.tsv'),
	(33, 'P.simiae', 'RCH2-oxoglutarate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-oxoglutarate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-oxoglutarate.xml', 'Growth', NULL, NULL, NULL),
	(34, 'P.simiae', 'RCH2-sucrose', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-sucrose.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-sucrose.xml', 'Growth', 'growth_file/RCH2-Sucrose.tsv', '5mM/5mM_sucrose.tsv', '20mM/20mM_sucrose.tsv'),
	(35, 'P.simiae', 'RCH2-xylose', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-xylose.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-xylose.xml', 'Growth', 'growth_file/RCH2-Xylose.tsv', '5mM/5mM_d-xylose.tsv', '20mM/20mM_d-xylose.tsv'),
	(36, 'P.simiae', 'RCH2-4-Hydroxybenzoate', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-4-Hydroxybenzoate.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-4-Hydroxybenzoate.xml', 'Growth', 'growth_file/RCH2-4-Hydroxybenzoate.tsv', NULL, NULL),
	(37, 'P.simiae', 'RCH2-TRHL', 'Model SEED', 'utrecht', 'PS_utrecht_gapfilled_RCH2-TRHL.xml', 'xml_files/PS_utrecht_gapfilled_RCH2-TRHL.xml', 'Growth', 'growth_file/RCH2-TRHL.tsv', NULL, NULL),
	(38, 'P.simiae', 'hydroxybenzoate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_hydroxybenzoate.xml', 'xml_files/PS_glucose-minimal_gapfilled_hydroxybenzoate.xml', 'Growth', 'growth_file/RCH2-4-Hydroxybenzoate.tsv', NULL, NULL),
	(39, 'P.simiae', 'galacturonate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_galacturonate.xml', 'xml_files/PS_glucose-minimal_gapfilled_galacturonate.xml', 'Growth', 'growth_file/RCH2-D-Galacturonate.tsv', NULL, NULL),
	(44, 'P.simiae', 'thymine', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_thymine.xml', 'xml_files/PS_glucose-minimal_gapfilled_thymine.xml', 'Growth', 'growth_file/RCH2-Thymine.tsv', '5mM/5mM_thymine.tsv', '20mM/20mM_thymine.tsv'),
	(45, 'P.simiae', 'oxoglutarate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_oxoglutarate.xml', 'xml_files/PS_glucose-minimal_gapfilled_oxoglutarate.xml', 'Growth', 'growth_file/RCH2-2-Oxoglutarate.tsv', NULL, NULL),
	(46, 'P.simiae', 'LACT', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_LACT.xml', 'xml_files/PS_glucose-minimal_gapfilled_LACT.xml', 'Growth', 'growth_file/RCH2-D-Galacturonate.tsv', '5mM/5mM_beta-lactose.tsv', '20mM/20mM_beta-lactose.tsv'),
	(47, 'P.simiae', 'l-arabinose', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_l-arabinose.xml', 'xml_files/PS_glucose-minimal_gapfilled_l-arabinose.xml', 'Growth', 'growth_file/RCH2-L-Arabinose.tsv', '5mM/5mM_l-arabinose.tsv', '20mM/20mM_l-arabinose.tsv'),
	(48, 'P.simiae', 'glucose6phosphate', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_glucose6phosphate.xml', 'xml_files/PS_glucose-minimal_gapfilled_glucose6phosphate.xml', 'Growth', NULL, NULL, NULL),
	(49, 'P.simiae', 'galactose', 'Model SEED', 'glucose-minimal', 'PS_glucose-minimal_gapfilled_galactose.xml', 'xml_files/PS_glucose-minimal_gapfilled_galactose.xml', 'Growth', 'growth_file/RCH2-Galactose.tsv', '5mM/5mM_d-galactose.tsv', '20mM/20mM_d-galactose.tsv'),
	(51, 'P.simiae', '2-deoxy-d-ribose', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_2-deoxy-d-ribose.tsv', '20mM/20mM_2-deoxy-d-ribose.tsv'),
	(52, 'P.simiae', '4-hydroxybenzoic_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_4-hydroxybenzoic_acid.tsv', '20mM/20mM_4-hydroxybenzoic_acid.tsv'),
	(53, 'P.simiae', '5-keto-d-gluconic_acid_potassium_salt', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_5-keto-d-gluconic_acid_potassium_salt.tsv', '20mM/20mM_5-keto-d-gluconic_acid_potassium_salt.tsv'),
	(54, 'P.simiae', 'a-cyclodextrin', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_a-cyclodextrin.tsv', '20mM/20mM_a-cyclodextrin.tsv'),
	(55, 'P.simiae', 'a-ketoglutaric_acid_disodium_salt_hydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_a-ketoglutaric_acid_disodium_salt_hydrate.tsv', '20mM/20mM_a-ketoglutaric_acid_disodium_salt_hydrate.tsv'),
	(56, 'P.simiae', 'adenine_hydrochloride_hydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_adenine_hydrochloride_hydrate.tsv', '20mM/20mM_adenine_hydrochloride_hydrate.tsv'),
	(57, 'P.simiae', 'adenosine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Adenosine.tsv', '5mM/5mM_adenosine.tsv', '20mM/20mM_adenosine.tsv'),
	(59, 'P.simiae', 'carnitine_hydrochloride', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_carnitine_hydrochloride.tsv', '20mM/20mM_carnitine_hydrochloride.tsv'),
	(60, 'P.simiae', 'casamino_acids', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_casamino_acids.tsv', '20mM/20mM_casamino_acids.tsv'),
	(61, 'P.simiae', 'citric_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_citric_acid.tsv', '20mM/20mM_citric_acid.tsv'),
	(63, 'P.simiae', 'cytosine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Cytosine.tsv', '5mM/5mM_cytosine.tsv', '20mM/20mM_cytosine.tsv'),
	(64, 'P.simiae', 'd,l-malic_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d,l-malic_acid.tsv', '20mM/20mM_d,l-malic_acid.tsv'),
	(65, 'P.simiae', 'd-alanine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-D-Alanine.tsv', '5mM/5mM_d-alanine.tsv', '20mM/20mM_d-alanine.tsv'),
	(67, 'P.simiae', 'd-cellobiose', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-cellobiose.tsv', '20mM/20mM_d-cellobiose.tsv'),
	(70, 'P.simiae', 'd-galacturonic_acid_monohydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-galacturonic_acid_monohydrate.tsv', '20mM/20mM_d-galacturonic_acid_monohydrate.tsv'),
	(71, 'P.simiae', 'd-gluconic_acid_sodium_salt', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-gluconic_acid_sodium_salt.tsv', '20mM/20mM_d-gluconic_acid_sodium_salt.tsv'),
	(72, 'P.simiae', 'd-glucosamine_hydrochloride', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-glucosamine_hydrochloride.tsv', '20mM/20mM_d-glucosamine_hydrochloride.tsv'),
	(75, 'P.simiae', 'd-glucuronic_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-glucuronic_acid.tsv', '20mM/20mM_d-glucuronic_acid.tsv'),
	(76, 'P.simiae', 'd-maltose_monohydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-maltose_monohydrate.tsv', '20mM/20mM_d-maltose_monohydrate.tsv'),
	(78, 'P.simiae', 'd-mannose', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-D-Mannose.tsv', '5mM/5mM_d-mannose.tsv', '20mM/20mM_d-mannose.tsv'),
	(79, 'P.simiae', 'd-raffinose_pentahydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-raffinose_pentahydrate.tsv', '20mM/20mM_d-raffinose_pentahydrate.tsv'),
	(80, 'P.simiae', 'd-ribose', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-D-Ribose.tsv', '5mM/5mM_d-ribose.tsv', '20mM/20mM_d-ribose.tsv'),
	(81, 'P.simiae', 'd-salicin', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-salicin.tsv', '20mM/20mM_d-salicin.tsv'),
	(82, 'P.simiae', 'd-serine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Serine.tsv', '5mM/5mM_d-serine.tsv', '20mM/20mM_d-serine.tsv'),
	(83, 'P.simiae', 'd-sorbitol', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Sorbitol.tsv', '5mM/5mM_d-sorbitol.tsv', '20mM/20mM_d-sorbitol.tsv'),
	(84, 'P.simiae', 'd-tagatose', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-tagatose.tsv', '20mM/20mM_d-tagatose.tsv'),
	(85, 'P.simiae', 'd-trehalose_dihydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_d-trehalose_dihydrate.tsv', '20mM/20mM_d-trehalose_dihydrate.tsv'),
	(87, 'P.simiae', 'ethanol', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Ethanol.tsv', '5mM/5mM_ethanol.tsv', '20mM/20mM_ethanol.tsv'),
	(88, 'P.simiae', 'gelatin', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_gelatin.tsv', '20mM/20mM_gelatin.tsv'),
	(89, 'P.simiae', 'glucuronamide', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_glucuronamide.tsv', '20mM/20mM_glucuronamide.tsv'),
	(90, 'P.simiae', 'gly-dl-asp', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_gly-dl-asp.tsv', '20mM/20mM_gly-dl-asp.tsv'),
	(91, 'P.simiae', 'gly-glu', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_gly-glu.tsv', '20mM/20mM_gly-glu.tsv'),
	(92, 'P.simiae', 'glycerol', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_glycerol.tsv', '20mM/20mM_glycerol.tsv'),
	(93, 'P.simiae', 'glycine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Glycine.tsv', '5mM/5mM_glycine.tsv', '20mM/20mM_glycine.tsv'),
	(94, 'P.simiae', 'glycolic_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_glycolic_acid.tsv', '20mM/20mM_glycolic_acid.tsv'),
	(95, 'P.simiae', 'inosine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Inosine.tsv', '5mM/5mM_inosine.tsv', '20mM/20mM_inosine.tsv'),
	(96, 'P.simiae', 'itaconic_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_itaconic_acid.tsv', '20mM/20mM_itaconic_acid.tsv'),
	(97, 'P.simiae', 'l-alanine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-D-Alanine.tsv', '5mM/5mM_l-alanine.tsv', '20mM/20mM_l-alanine.tsv'),
	(99, 'P.simiae', 'l-arginine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Arginine.tsv', '5mM/5mM_l-arginine.tsv', '20mM/20mM_l-arginine.tsv'),
	(100, 'P.simiae', 'l-asparagine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Asparagine.tsv', '5mM/5mM_l-asparagine.tsv', '20mM/20mM_l-asparagine.tsv'),
	(101, 'P.simiae', 'l-aspartic_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_l-aspartic_acid.tsv', '20mM/20mM_l-aspartic_acid.tsv'),
	(103, 'P.simiae', 'l-cysteine_hydrochloride_monohydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_l-cysteine_hydrochloride_monohydrate.tsv', '20mM/20mM_l-cysteine_hydrochloride_monohydrate.tsv'),
	(104, 'P.simiae', 'l-fucose', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Fucose.tsv', '5mM/5mM_l-fucose.tsv', '20mM/20mM_l-fucose.tsv'),
	(105, 'P.simiae', 'l-glutamic_acid_monopotassium_salt_monohydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_l-glutamic_acid_monopotassium_salt_monohydrate.tsv', '20mM/20mM_l-glutamic_acid_monopotassium_salt_monohydrate.tsv'),
	(106, 'P.simiae', 'l-glutamine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Glutamine.tsv', '5mM/5mM_l-glutamine.tsv', '20mM/20mM_l-glutamine.tsv'),
	(107, 'P.simiae', 'l-histidine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Histidine.tsv', '5mM/5mM_l-histidine.tsv', '20mM/20mM_l-histidine.tsv'),
	(108, 'P.simiae', 'l-isoleucine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Isoleucine.tsv', '5mM/5mM_l-isoleucine.tsv', '20mM/20mM_l-isoleucine.tsv'),
	(109, 'P.simiae', 'l-leucine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Leucine.tsv', '5mM/5mM_l-leucine.tsv', '20mM/20mM_l-leucine.tsv'),
	(110, 'P.simiae', 'l-lysine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Lysine.tsv', '5mM/5mM_l-lysine.tsv', '20mM/20mM_l-lysine.tsv'),
	(111, 'P.simiae', 'l-malic_acid_disodium_salt_monohydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_l-malic_acid_disodium_salt_monohydrate.tsv', '20mM/20mM_l-malic_acid_disodium_salt_monohydrate.tsv'),
	(112, 'P.simiae', 'l-methionine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Methionine.tsv', '5mM/5mM_l-methionine.tsv', '20mM/20mM_l-methionine.tsv'),
	(114, 'P.simiae', 'l-proline', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Proline.tsv', '5mM/5mM_l-proline.tsv', '20mM/20mM_l-proline.tsv'),
	(115, 'P.simiae', 'l-rhamnose_monohydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_l-rhamnose_monohydrate.tsv', '20mM/20mM_l-rhamnose_monohydrate.tsv'),
	(116, 'P.simiae', 'l-serine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Serine.tsv', '5mM/5mM_l-serine.tsv', '20mM/20mM_l-serine.tsv'),
	(117, 'P.simiae', 'l-sorbose', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_l-sorbose.tsv', '20mM/20mM_l-sorbose.tsv'),
	(118, 'P.simiae', 'l-threonine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Threonine.tsv', '5mM/5mM_l-threonine.tsv', '20mM/20mM_l-threonine.tsv'),
	(120, 'P.simiae', 'l-tyrosine_disodium_salt', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_l-tyrosine_disodium_salt.tsv', '20mM/20mM_l-tyrosine_disodium_salt.tsv'),
	(121, 'P.simiae', 'l-valine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Valine.tsv', '5mM/5mM_l-valine.tsv', '20mM/20mM_l-valine.tsv'),
	(122, 'P.simiae', 'm-inositol', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_m-inositol.tsv', '20mM/20mM_m-inositol.tsv'),
	(124, 'P.simiae', 'parabanic_acid', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_parabanic_acid.tsv', '20mM/20mM_parabanic_acid.tsv'),
	(126, 'P.simiae', 'potassium_oxalate_monohydrate', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_potassium_oxalate_monohydrate.tsv', '20mM/20mM_potassium_oxalate_monohydrate.tsv'),
	(127, 'P.simiae', 'putrescine_dihydrochloride', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_putrescine_dihydrochloride.tsv', '20mM/20mM_putrescine_dihydrochloride.tsv'),
	(128, 'P.simiae', 'sodium_butyrate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Butyrate.tsv', '5mM/5mM_sodium_butyrate.tsv', '20mM/20mM_sodium_butyrate.tsv'),
	(131, 'P.simiae', 'sodium_formate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Formate.tsv', '5mM/5mM_sodium_formate.tsv', '20mM/20mM_sodium_formate.tsv'),
	(132, 'P.simiae', 'sodium_fumarate_dibasic', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_sodium_fumarate_dibasic.tsv', '20mM/20mM_sodium_fumarate_dibasic.tsv'),
	(133, 'P.simiae', 'sodium_l-lactate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-D-Lactate.tsv', '5mM/5mM_sodium_l-lactate.tsv', '20mM/20mM_sodium_l-lactate.tsv'),
	(136, 'P.simiae', 'sodium_pyruvate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Pyruvate.tsv', '5mM/5mM_sodium_pyruvate.tsv', '20mM/20mM_sodium_pyruvate.tsv'),
	(139, 'P.simiae', 'thymidine', 'Model SEED', NULL, '', NULL, '', NULL, '5mM/5mM_thymidine.tsv', '20mM/20mM_thymidine.tsv'),
	(243, 'P.simiae', 'RCH2-Adenine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Adenine.tsv', NULL, NULL),
	(246, 'P.simiae', 'RCH2-Carnitine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Carnitine.tsv', NULL, NULL),
	(254, 'P.simiae', 'RCH2-D-Glucose', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-D-Glucose.tsv', NULL, NULL),
	(260, 'P.simiae', 'RCH2-D-glucose-6-phosphate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-D-glucose-6-phosphate.tsv', NULL, NULL),
	(263, 'P.simiae', 'RCH2-Fumarate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Fumarate.tsv', NULL, NULL),
	(264, 'P.simiae', 'RCH2-GLCN', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-GLCN.tsv', NULL, NULL),
	(265, 'P.simiae', 'RCH2-GLUM', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-GLUM.tsv', NULL, NULL),
	(269, 'P.simiae', 'RCH2-Glycolate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Glycolate.tsv', NULL, NULL),
	(272, 'P.simiae', 'RCH2-L-Alanine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Alanine.tsv', NULL, NULL),
	(276, 'P.simiae', 'RCH2-L-Aspartate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Aspartate.tsv', NULL, NULL),
	(277, 'P.simiae', 'RCH2-L-Cysteine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Cysteine.tsv', NULL, NULL),
	(279, 'P.simiae', 'RCH2-L-Glutamate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Glutamate.tsv', NULL, NULL),
	(287, 'P.simiae', 'RCH2-L-Malate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Malate.tsv', NULL, NULL),
	(294, 'P.simiae', 'RCH2-L-Tyrosine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-L-Tyrosine.tsv', NULL, NULL),
	(296, 'P.simiae', 'RCH2-Maltose', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Maltose.tsv', NULL, NULL),
	(298, 'P.simiae', 'RCH2-Oxalate', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Oxalate.tsv', NULL, NULL),
	(300, 'P.simiae', 'RCH2-Putrescine', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-Putrescine.tsv', NULL, NULL),
	(310, 'P.simiae', 'RCH2-gly-glu-L', 'Model SEED', NULL, '', NULL, '', 'growth_file/RCH2-gly-glu-L.tsv', NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
